import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hola soy <a href="https://nextjs.org">Fabian Molina!</a>
        </h1>
        <Link href="/timeline"> Time Line</Link>
      </main>
    </div>
  )
}

export default Home
